# ================= Eureka Client Config =================
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}

# ================= Service URI Config =================
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payments/doPayment
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder

# ================= Prometheus / Actuator Config =================
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
